server:
  port: 8081

spring:
  application:
    name: auth-service

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
